version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile-dev
      context: ./server
    
    volumes:
      - ./server:/app

    container_name: project_server

    ports:
      - "5000:5000"

    depends_on:
      - mysql


  mysql:
    build: ./mysql

    restart: unless-stopped

    container_name: project_mysql

    ports:
      - "3306:3306"
    
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: final_project
