version: "3"
    
# services:
#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#     ports:
#       - '80:80'
#       - '443:443'
#     restart: always


#   certbot:
#     image: certbot/certbot
#     volumes:
#       - ./certbot/conf:/etc/letsencrypt:rw
#       - ./certbot/www:/var/www/certbot:rw

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot